name: DCO Check

on:
  pull_request:

jobs:
  dco:
    name: DCO Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: DCO Check
        run: |
          base_sha="${{ github.event.pull_request.base.sha }}"
          echo "Base SHA: $base_sha"
          head_sha="${{ github.event.pull_request.head.sha }}"
          echo "Head SHA: $head_sha"
          echo "---"
          commits="$(git rev-list --ancestry-path $base_sha..$head_sha)"
          echo "Analyzing:"
          fail=0
          dco_check="$(git show --no-patch --format="%B" "$base_sha" | grep 'Signed-off-by:')"
          if [ -z "$dco_check" ]; then
              echo "Commit $base_sha is missing the DCO sign-off!"
              fail=1
          fi
          echo "$base_sha passed"
          
          commits="$(git rev-list --ancestry-path $base_sha..$head_sha)"
          for commit in $commits; do
          dco_check="$(git show --no-patch --format="%B" "$commit" | grep 'Signed-off-by:')"
          if [ -z "$dco_check" ]; then
              printf "\e[31m$commit failed\e[0m\n"
              fail=1
          fi
          echo "$commit passed"
          done
          
          if [ "$fail" -ne 0 ]; then
              echo "Failures found"
              exit 1
          fi
          
          echo "---"
          echo "All commits have DCO signed-off"
